### ISSUE TITLE
Dependence on number of objects plotted

### ISSUE THREAD

**Issue by mpadge** [thomasp85/plotting_benchmark#1]
Great investigations @thomasp85! This is not really an issue, just a pointer to a potentially helpful insight. I previously did a benchmark of `svglite` output of `ggplot` objects against the theoretically fastest possible `svg` rendering (of data only, via internal C++ code). The interesting result in the context of what you've done here is the roughly bi-linear response seen in the first graph [at the end of the `README`](https://github.com/hypertidy/svgplotr).

You've chosen values generally around `1e3`-`1e4`, which is well within the first, steep portion of the bi-linear response. The results I generated suggest you'd get different results if you extended these values beyond about `1e5`. It might be interesting to know how your comparisons would then look once the "constant" overhead of exporting the non-data bits of the graphic object became relatively insignificant compared to numbers of individual objects to be plotted? Exporting `1e6` lines via `svglite` actually becomes pretty efficient, at only around 4 times slower than the absolute theoretically fastest limit.

**Comment by thomasp85** [comment]
Thanks for the insight! My first focus is less on the efficiency of the devices themselves but it is certainly an area that needs attention (both how the perform generally and how they scale)... I'm generally surprised about the time spend by the graphic devices - I had suspected it would be negligible...

**Comment by mpadge** [comment]
Yeah, it is surprising how enormous it is. The time spent by `svglite` just translating and exporting the `ggplot` meta-data is enormous, but as you say, you get a lot of `gg`-power for that. Anyway, I'll close this and leave you to it. Thanks!
